blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/slavasuhoveev/shelf-auth/discussions
    about: Please use GitHub Discussions for questions and support
