name: Task
description: General development task
title: "[Task]: "
labels: ["type:task"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Provide a clear and concise description of the task.
    validations:
      required: true

  - type: textarea
    id: equirements
    attributes:
      label: Requirements
      description: Technical requirements and constraints, step-by-step checklist.
      placeholder: |
        - [ ] First criterion
        - [ ] Second criterion
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Conditions that must be met for this task to be considered complete.
      placeholder: |
        - [ ] First criterion
        - [ ] Second criterion
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      description: Checklist to ensure the task is fully completed.
      placeholder: |
        - [ ] Code implemented
        - [ ] Tests written and passing
        - [ ] Documentation updated
    validations:
      required: true
